### ISSUE TITLE
StreamDeck Mini Support

### ISSUE THREAD

**Issue by Sherlouk** [Sherlouk/Codedeck#5]
I currently only have a full sized StreamDeck so testing on the Mini is not possible but I'd still love to support it eventually.

Having read issues on the [node-elgato-stream-deck](https://github.com/Lange/node-elgato-stream-deck/issues) repository it does look like a few things are different.

**Comment by Joebayld** [comment]
I'd like to see this support the mini.. Any ideas on where to begin here?

**Comment by Sherlouk** [comment]
I believe quite a few things changed in the communication between the two devices so this would likely not be an easy introduction. Would need to start by identifying all of the packets that are getting transferred, what they mean, and then start implementing switches in order to toggle between the two devices behaviours.

Not sure if something like [this](https://gaming.help.elgato.com/customer/en/portal/articles/2965624-elgato-stream-deck-sdk-%E2%80%93-use-software-version-4-0-and-above) would work better for your case? This project is kinda unnecessary now!

**Comment by Sherlouk** [comment]
Thank you for your **huge** contributions here Joe. I'll be merging this in under #15.
